language:
  python

python:
  - 3.6

install:
  - ./tools/generate_key_pair.sh
  - make install

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - curl -s https://raw.githubusercontent.com/datahq/deploy/master/apps_travis_script.sh > .travis.sh

deploy:
  - provider: script
    script: bash .travis.sh trigger datahub-auth
    on:
      branch: master
  - provider: script
    script: bash .travis.sh trigger specstore
    on:
      branch: master
  - provider: script
    script: bash .travis.sh trigger bitstore
    on:
      branch: master
