language:
  python

python:
  - 3.6

env:
  global:
    - TRIGGER_REPO=datahub-auth

install:
  - ./tools/generate_key_pair.sh
  - make install

script:
  - make test
  - curl -s https://raw.githubusercontent.com/datahq/deploy/master/apps_travis_script.sh > .travis.sh

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh trigger
  on:
    branch: master
